/**
 * component-spec.js
 * 共享组件数据模型（GitLab Pajamas 风格）。所有框架生成器读取此文件，
 * 保证 10 个核心组件在每种技术栈中实现一致的 Props / 状态 / 设计令牌。
 * 令牌一律引用 CSS 变量（var(--gl-*)），真正的值定义在 dist/css/variables.css。
 */
module.exports = {
  meta: {
    brand: 'Pajamas-inspired',
    license: 'MIT',
    source: '@gitlab/ui design tokens',
    css: '../../css/variables.css', // 相对各框架 components 目录
  },
  components: [
    {
      id: 'button',
      title: 'Button',
      description: '主要交互按钮。视觉层级 category=primary|secondary|tertiary；语义 variant=default|confirm|danger|link。',
      importsCssVar: true,
      props: [
        { name: 'category', type: 'primary|secondary|tertiary', default: 'primary', desc: '视觉层级' },
        { name: 'variant', type: 'default|confirm|danger|link', default: 'default', desc: '语义色' },
        { name: 'size', type: 'small|medium', default: 'medium', desc: '尺寸' },
        { name: 'disabled', type: 'boolean', default: false, desc: '禁用' },
        { name: 'loading', type: 'boolean', default: false, desc: '加载中（显示 spinner）' },
        { name: 'icon', type: 'string', default: '', desc: '图标名' },
        { name: 'block', type: 'boolean', default: false, desc: '整宽' },
      ],
      states: ['default', 'hover', 'active', 'focus', 'disabled', 'loading'],
      tokens: [
        '--gl-button-border-radius', '--gl-button-default-primary-background-color-default',
        '--gl-button-default-primary-foreground-color-default', '--gl-button-confirm-primary-background-color-default',
        '--gl-button-confirm-primary-foreground-color-default', '--gl-button-danger-primary-background-color-default',
        '--gl-button-danger-primary-foreground-color-default', '--gl-action-disabled-background-color',
        '--gl-action-disabled-foreground-color', '--gl-border-color-default', '--gl-spacing-scale-3',
        '--gl-spacing-scale-4', '--gl-font-size-sm',
      ],
      cssClass: 'gl-button gl-button-icon gl-button-text',
      example: 'confirm 实心主按钮；danger 用于破坏性操作；tertiary 为文字按钮。',
    },
    {
      id: 'input',
      title: 'Input',
      description: '文本输入框。支持校验态 state=valid|invalid|null、宽度档位、占位符、禁用/只读。',
      importsCssVar: true,
      props: [
        { name: 'type', type: 'text|email|number|password|search|url|tel|date|time', default: 'text', desc: '输入类型' },
        { name: 'placeholder', type: 'string', default: '', desc: '占位符' },
        { name: 'state', type: 'valid|invalid|null', default: null, desc: '校验态' },
        { name: 'disabled', type: 'boolean', default: false, desc: '禁用' },
        { name: 'readonly', type: 'boolean', default: false, desc: '只读' },
        { name: 'width', type: 'xs|sm|md|lg|xl|null', default: null, desc: '宽度档' },
      ],
      states: ['default', 'hover', 'focus', 'valid', 'invalid', 'disabled', 'readonly'],
      tokens: [
        '--gl-control-border-color-default', '--gl-control-border-color-hover', '--gl-control-border-color-focus',
        '--gl-control-border-color-error', '--gl-control-background-color-default', '--gl-control-placeholder-color',
        '--gl-control-text-color-error', '--gl-control-text-color-valid', '--gl-focus-ring-outer-color',
      ],
      cssClass: 'gl-form-input form-control gl-form-input-md',
      example: 'invalid 态显示红边框 + 错误文字；focus 使用 2px 焦点环。',
    },
    {
      id: 'modal',
      title: 'Modal',
      description: '模态对话框。尺寸 sm|md|lg，标题 + 正文 + footer 操作按钮（primary/secondary/cancel）。',
      importsCssVar: true,
      props: [
        { name: 'visible', type: 'boolean', default: false, desc: '显隐（v-model）' },
        { name: 'title', type: 'string', default: '', desc: '标题' },
        { name: 'size', type: 'sm|md|lg', default: 'md', desc: '尺寸' },
        { name: 'primaryAction', type: '{text, variant}', default: null, desc: '主按钮' },
        { name: 'secondaryAction', type: '{text}', default: null, desc: '次按钮' },
        { name: 'onClose', type: 'function', default: null, desc: '关闭回调' },
      ],
      states: ['closed', 'opened', 'entering', 'leaving'],
      tokens: [
        '--gl-modal-border-radius', '--gl-modal-medium-width', '--gl-shadow-lg',
        '--gl-color-alpha-dark-40', '--gl-heading-scale-500-font-size', '--gl-spacing-scale-5',
        '--gl-spacing-scale-3', '--gl-font-size-base', '--gl-zindex-modal',
      ],
      cssClass: 'gl-modal modal-backdrop gl-bg-overlay',
      example: '遮罩点击/Esc/× 关闭；footer 按钮左对齐、小屏纵向排列。',
    },
    {
      id: 'table',
      title: 'Table',
      description: '数据表格。支持排序表头、busy 加载态、行 hover 高亮、空状态。',
      importsCssVar: true,
      props: [
        { name: 'items', type: 'array', default: '[]', desc: '行数据' },
        { name: 'fields', type: 'array', default: '[]', desc: '列定义 [{key,label,sortable}]' },
        { name: 'loading', type: 'boolean', default: false, desc: 'busy 态' },
        { name: 'sortBy', type: 'string', default: null, desc: '排序列' },
        { name: 'sortDesc', type: 'boolean', default: false, desc: '降序' },
      ],
      states: ['default', 'loading', 'sorted', 'row-hover', 'empty'],
      tokens: [
        '--gl-table-row-background-color-hover', '--gl-table-sorting-icon-color',
        '--gl-border-color-default', '--gl-color-alpha-0', '--gl-spacing-scale-3',
        '--gl-text-subtle-color', '--gl-font-weight-bold',
      ],
      cssClass: 'gl-table gl-table--sticky-header',
      example: '表头下方 1px 分割线，可排序列显示 ↑/↓ 箭头。',
    },
    {
      id: 'tabs',
      title: 'Tabs',
      description: '标签页导航。激活项带底部指示条，可带计数 badge，支持按钮动作。',
      importsCssVar: true,
      props: [
        { name: 'tabs', type: 'array', default: '[]', desc: '[{title, count?, content}]' },
        { name: 'active', type: 'number', default: 0, desc: '激活索引' },
        { name: 'onChange', type: 'function', default: null, desc: '切换回调' },
      ],
      states: ['default', 'active', 'hover', 'disabled'],
      tokens: [
        '--gl-tab-selected-indicator-color-default', '--gl-border-color-default',
        '--gl-border-color-strong', '--gl-action-disabled-foreground-color',
        '--gl-text-base-font-size', '--gl-font-weight-bold', '--gl-spacing-scale-4',
      ],
      cssClass: 'gl-tabs gl-tabs-wrapper gl-tab-nav-item gl-tab-content',
      example: '导航下方整条 border；激活指示条为 2px 蓝色条。',
    },
    {
      id: 'badge',
      title: 'Badge',
      description: '胶囊状态标签。variant=neutral|info|success|warning|danger|tier，可带图标、可链接。',
      importsCssVar: true,
      props: [
        { name: 'variant', type: 'neutral|info|success|warning|danger|tier', default: 'neutral', desc: '语义色' },
        { name: 'icon', type: 'string', default: null, desc: '图标名' },
        { name: 'href', type: 'string', default: null, desc: '链接' },
      ],
      states: ['default', 'hover', 'active', 'disabled'],
      tokens: [
        '--gl-badge-neutral-background-color-default', '--gl-badge-info-background-color-default',
        '--gl-badge-success-background-color-default', '--gl-badge-warning-background-color-default',
        '--gl-badge-danger-background-color-default', '--gl-border-radius-full',
        '--gl-text-sm-font-size', '--gl-spacing-scale-1', '--gl-spacing-scale-2',
      ],
      cssClass: 'gl-badge badge badge-pill',
      example: 'pill 全圆角胶囊；链接时 hover 加内描边。',
    },
    {
      id: 'toast',
      title: 'Toast',
      description: '左下角轻量通知。自动隐藏（默认 5s），可带一个操作按钮。',
      importsCssVar: true,
      props: [
        { name: 'message', type: 'string', default: '', desc: '正文' },
        { name: 'action', type: '{text, onClick}', default: null, desc: '操作按钮' },
        { name: 'autoHideDelay', type: 'number', default: 5000, desc: 'ms' },
        { name: 'onDismiss', type: 'function', default: null, desc: '关闭回调' },
      ],
      states: ['visible', 'entering', 'leaving'],
      tokens: [
        '--gl-feedback-strong-background-color', '--gl-feedback-strong-text-color',
        '--gl-feedback-strong-link-color', '--gl-shadow-md', '--gl-border-radius-full',
        '--gl-spacing-scale-5', '--gl-spacing-scale-6',
      ],
      cssClass: 'gl-toast b-toaster-bottom-left',
      example: 'fixed 底部左侧堆叠；深色底高对比文本。',
    },
    {
      id: 'dropdown',
      title: 'Dropdown',
      description: '下拉菜单。支持头部、勾选项、分割线、清除全部。',
      importsCssVar: true,
      props: [
        { name: 'text', type: 'string', default: '', desc: '触发按钮文本' },
        { name: 'items', type: 'array', default: '[]', desc: '菜单项' },
        { name: 'showClearAll', type: 'boolean', default: false, desc: '清除全部' },
        { name: 'onSelect', type: 'function', default: null, desc: '选择回调' },
      ],
      states: ['closed', 'opened', 'item-hover', 'item-checked'],
      tokens: [
        '--gl-dropdown-background-color', '--gl-dropdown-divider-color', '--gl-dropdown-border-color',
        '--gl-dropdown-border-radius', '--gl-shadow-sm', '--gl-text-base-font-size',
        '--gl-spacing-scale-4', '--gl-color-alpha-dark-4',
      ],
      cssClass: 'gl-dropdown dropdown-menu dropdown-toggle',
      example: '菜单浮层带阴影 + 圆角；勾选项右侧 check 图标。',
    },
    {
      id: 'form',
      title: 'Form / FormGroup',
      description: '表单容器与字段组：label + 输入 + 校验反馈 + 帮助文本，字段间距统一。',
      importsCssVar: true,
      props: [
        { name: 'label', type: 'string', default: '', desc: '字段标签' },
        { name: 'helper', type: 'string', default: '', desc: '帮助文本' },
        { name: 'error', type: 'string', default: null, desc: '错误信息' },
        { name: 'optional', type: 'boolean', default: false, desc: '可选标记' },
      ],
      states: ['default', 'valid', 'invalid', 'disabled'],
      tokens: [
        '--gl-control-text-color-error', '--gl-control-text-color-valid',
        '--gl-text-strong-color', '--gl-text-subtle-color', '--gl-font-weight-bold',
        '--gl-font-size-base', '--gl-spacing-scale-2', '--gl-spacing-scale-5',
      ],
      cssClass: 'gl-form-group col-form-label label-description',
      example: 'label 粗体；error 显示红字反馈；字段间距 mb-5。',
    },
    {
      id: 'alert',
      title: 'Alert',
      description: '嵌入式提示条。variant=info|success|warning|danger|tip，带图标、标题、可关闭、可吸顶。',
      importsCssVar: true,
      props: [
        { name: 'variant', type: 'info|success|warning|danger|tip', default: 'info', desc: '语义色' },
        { name: 'title', type: 'string', default: '', desc: '标题' },
        { name: 'dismissible', type: 'boolean', default: true, desc: '可关闭' },
        { name: 'sticky', type: 'boolean', default: false, desc: '吸顶' },
      ],
      states: ['default', 'dismissing'],
      tokens: [
        '--gl-alert-border-radius', '--gl-alert-info-background-color', '--gl-alert-info-title-color',
        '--gl-alert-danger-background-color', '--gl-alert-danger-title-color',
        '--gl-alert-warning-background-color', '--gl-alert-warning-title-color',
        '--gl-alert-success-background-color', '--gl-alert-success-title-color',
        '--gl-feedback-info-icon-color', '--gl-feedback-danger-icon-color',
      ],
      cssClass: 'gl-alert gl-alert-icon-container gl-alert-title',
      example: '左侧图标 + 内容区；1px 边框 + 圆角；danger 加 role=alert。',
    },
  ],
};